### ISSUE TITLE
Thread scanned project files probably hangs

### ISSUE THREAD

**Issue by jaclas** [rfrezino/RFindUnit#29]
See screen:

https://snap.ashampoo.com/uploads/2016-02-24/73Xm6hsF.png

after 8h IDE working...

**Comment by rfrezino** [comment]
I'm trying to reproduce it, but no success. I already had the same error here, I'm trying to figure out what is happening. Some hint ?

**Comment by rfrezino** [comment]
I sent some modifications now, can you try it ?

**Comment by jaclas** [comment]
MAINICON ICON "RFindUnit_Icon.ico" <-- file not found 

in RFindUnit\RFindUnit.vrc file :-)

**Comment by jaclas** [comment]
Maybe problem is that I work on Project Group?

**Comment by rfrezino** [comment]
hun.... maybe, I'll try to test with Project Group
vrc file ? I don't have it here

**Comment by jaclas** [comment]
After delete all source files and update from repository, and build and install expert again... this act.
But when I click refresh library files then I get AV with callstack:

(000029B8){            } [000239B8]
[1E5053B9]{RFindUnit.bpl} Otlcontainersfu.TOmniBaseBoundedQueue.MeasureExecutionTimes + $19D
[50063D44]{rtl230.bpl  } System.@FinalizeArray (Line 31928, "System.pas" + 139) + $0
[50063D34]{rtl230.bpl  } System.@FinalizeArray (Line 31916, "System.pas" + 127) + $0
[50994108]{vcl230.bpl  } Vcl.Controls.TControl.CMVisibleChanged (Line 7594, "Vcl.Controls.pas" + 2) + $14
[50993529]{vcl230.bpl  } Vcl.Controls.TControl.WndProc (Line 7249, "Vcl.Controls.pas" + 91) + $6
[50067110]{rtl230.bpl  } System.@IntfClear (Line 36551, "System.pas" + 10) + $0
[1E51D4A7]{RFindUnit.bpl} Otltaskcontrolfu.TOmniTaskControl.Invoke + $1B7
[50063D44]{rtl230.bpl  } System.@FinalizeArray (Line 31928, "System.pas" + 139) + $0
[50063C34]{rtl230.bpl  } System.@FinalizeRecord (Line 31631, "System.pas" + 25) + $0
[1E50EEBC]{RFindUnit.bpl} Otlthreadpoolfu.TOmniThreadPoolMonitorInfo + $3C48
[509967D9]{vcl230.bpl  } Vcl.Controls.TWinControl.GetControl (Line 9165, "Vcl.Controls.pas" + 3) + $4
[509A4DFA]{vcl230.bpl  } Vcl.StdCtrls..TGroupBox + $2
[50995CF0]{vcl230.bpl  } Vcl.Controls.AlignWork (Line 8782, "Vcl.Controls.pas" + 3) + $13
[509960A5]{vcl230.bpl  } Vcl.Controls.TWinControl.AlignControls (Line 8888, "Vcl.Controls.pas" + 5) + $1
[5099629E]{vcl230.bpl  } Vcl.Controls.TWinControl.AlignControl (Line 8958, "Vcl.Controls.pas" + 9) + $A
[5005A180]{rtl230.bpl  } System.@GetMem (Line 4596, "System.pas" + 20) + $0
[1E5634B7]{RFindUnit.bpl} Findunit.Worker.TParserWorker.GetItemsToParse + $1F
[1E565524]{RFindUnit.bpl} Findunit.Environmentcontroller.TEnvironmentController.GetLibraryPathStatus + $3C
[50990C90]{vcl230.bpl  } Vcl.Controls.TControl.RequestAlign (Line 5536, "Vcl.Controls.pas" + 1) + $1
[50991B06]{vcl230.bpl  } Vcl.Controls.TControl.SetVisible (Line 6057, "Vcl.Controls.pas" + 9) + $4
[1E56D7FC]{RFindUnit.bpl} Findunit.Formsearch.TfrmFindUnit.CheckLoadingStatus + $68
[1E56E2BA]{RFindUnit.bpl} Findunit.Formsearch.TfrmFindUnit.CheckLibraryStatus + $72
[1E56D6A1]{RFindUnit.bpl} Findunit.Formsearch.TfrmFindUnit.btnRefreshLibraryPathClick + $1D
[50993A97]{vcl230.bpl  } Vcl.Controls.TControl.Click (Line 7365, "Vcl.Controls.pas" + 9) + $8
[50B241E8]{vcl230.bpl  } Vcl.Buttons.TSpeedButton.Click (Line 1549, "Vcl.Buttons.pas" + 0) + $0
[50B241D2]{vcl230.bpl  } Vcl.Buttons.TSpeedButton.MouseUp (Line 1542, "Vcl.Buttons.pas" + 25) + $C
[50993ED0]{vcl230.bpl  } Vcl.Controls.TControl.DoMouseUp (Line 7493, "Vcl.Controls.pas" + 2) + $28
[50993F50]{vcl230.bpl  } Vcl.Controls.TControl.WMLButtonUp (Line 7506, "Vcl.Controls.pas" + 9) + $6
[50993529]{vcl230.bpl  } Vcl.Controls.TControl.WndProc (Line 7249, "Vcl.Controls.pas" + 91) + $6
(0003E0DE){CnWizards_D10S.dll} [1303F0DE]
(0003B732){CnWizards_D10S.dll} [1303C732]
[50993164]{vcl230.bpl  } Vcl.Controls.TControl.Perform (Line 7027, "Vcl.Controls.pas" + 10) + $8
[50997914]{vcl230.bpl  } Vcl.Controls.TWinControl.IsControlMouseMsg (Line 9856, "Vcl.Controls.pas" + 15) + $29
[50997ECA]{vcl230.bpl  } Vcl.Controls.TWinControl.WndProc (Line 10025, "Vcl.Controls.pas" + 104) + $6
[50997688]{vcl230.bpl  } Vcl.Controls.TWinControl.MainWndProc (Line 9786, "Vcl.Controls.pas" + 3) + $6
[5017252C]{rtl230.bpl  } System.Classes.StdWndProc (Line 16881, "System.Classes.pas" + 8) + $0
[50067B4C]{rtl230.bpl  } System.UTF8ToUnicodeString (Line 37899, "System.pas" + 12) + $10
[50ADE229]{vcl230.bpl  } Vcl.Forms.TApplication.CancelHint (Line 11267, "Vcl.Forms.pas" + 6) + $D
[50ADCEBB]{vcl230.bpl  } Vcl.Forms.TApplication.ProcessMessage (Line 10438, "Vcl.Forms.pas" + 23) + $1
[50ADCEFE]{vcl230.bpl  } Vcl.Forms.TApplication.HandleMessage (Line 10468, "Vcl.Forms.pas" + 1) + $4
[50ADD231]{vcl230.bpl  } Vcl.Forms.TApplication.Run (Line 10606, "Vcl.Forms.pas" + 26) + $3


Additionaly... when I install expert in IDE, after click "Install" in project manager context menu Delphi IDE... dissapear (close without any message). But installed ok. Strange.

**Comment by jaclas** [comment]
Unfortunately, it is still wrong. After restart IDE on the label is the caption "Ready" (button "Refresh" is hidden) and the expert does not found anything in my code.

**Comment by rfrezino** [comment]
jaclas, I was a little busy developing the DCU watcher, I've just merged it on main branch. 
Now I'll take a more deeply look on you problem

**Comment by rfrezino** [comment]
Fixed!

**Comment by jaclas** [comment]
Unfortunately, the problem still exist :-(
https://snap.ashampoo.com/uploads/2016-04-04/dNVoFxMx.png

**Comment by rfrezino** [comment]
Hi jaclas, are you sure you installed the new version ?
I odd an Version identifier on the caption of search form. Please download the new version and check if your version is 1.0.1
thanks

**Comment by jaclas** [comment]
Sad, but true :-)
https://snap.ashampoo.com/uploads/2016-04-05/lAwJbpYm.png

**Comment by rfrezino** [comment]
urghhh! Some hint ? It can't reproduce it here!

**Comment by rfrezino** [comment]
Tell me about your kind of project, does it is a group project? dll ? standard ?

**Comment by jaclas** [comment]
I use Group Project. 
Maybe add more information to the logger please, and I will send a log file?

**Comment by rfrezino** [comment]
please, take a pic of your project group (the right side on IDE) and send me de log that you have. 
%appdata%\DelphiFindUnit\Logger, (last modified doc)

**Comment by jaclas** [comment]
https://snap.ashampoo.com/uploads/2016-04-06/GY4b6K4l.png


[pdi_4304_log_2016-04-06.txt](https://github.com/rfrezino/RFindUnit/files/206551/pdi_4304_log_2016-04-06.txt)

**Comment by rfrezino** [comment]
jaclas, I did I change on project, please update and check. I don't think it will solve the problem buttttt

**Comment by jaclas** [comment]
... but still is problem :-)

[pdi_924_log_2016-04-06.txt](https://github.com/rfrezino/RFindUnit/files/206601/pdi_924_log_2016-04-06.txt)

Now I leave work, I come back tomorrow, and you think over these extended logs ;-)

**Comment by rfrezino** [comment]
I odd some debug logs

**Comment by jaclas** [comment]
I too added an additional logs and it looks like in my project is not invoked this method:

```
procedure TEnvironmentController.CreatingProject(const ProjectOrGroup: IOTAModule);
begin
  Logger.Debug('TEnvironmentController.CreatingProject');
  LoadProjectPath;
end;
```

See log:


[pdi_11028_log_2016-04-07.txt](https://github.com/rfrezino/RFindUnit/files/207867/pdi_11028_log_2016-04-07.txt)
ps. Sometimes the "Install" or "Uninstall" package closes unexpectedly Delphi.

**Comment by rfrezino** [comment]
hun..................................................................... ! Maybe they change something on new OTA.
Please send me your ToolsApi.pas file, rodrigofrezino@gmail.com

**Comment by rfrezino** [comment]
Jaclas, I forced the load library, download and try it please

**Comment by jaclas** [comment]
This is crazy, but still is problem :-)

[pdi_808_log_2016-04-07.txt](https://github.com/rfrezino/RFindUnit/files/208900/pdi_808_log_2016-04-07.txt)

**Comment by rfrezino** [comment]
No way hahahah Sent new version, please, download, build, install and send me the logs!

**Comment by rfrezino** [comment]
Do you have skype ? ou hangouts ?

**Comment by jaclas** [comment]
[pdi_7108_log_2016-04-07.txt](https://github.com/rfrezino/RFindUnit/files/208934/pdi_7108_log_2016-04-07.txt)

[ToolsAPI.txt](https://github.com/rfrezino/RFindUnit/files/208938/ToolsAPI.txt)

**Comment by rfrezino** [comment]
wowww! Are you opening the project directly from dpr file ? 
For example, double click on dpr ? Or from Delphi IDE ?

**Comment by rfrezino** [comment]
I could reproduce with double clicking on dpr file! Fixed! Check!

**Comment by jaclas** [comment]
Hmm... probably It's all right, congratulations Rodrigo! And thanks :-)

**Comment by jaclas** [comment]
Please add checkbox for on/off log to file.
