### ISSUE TITLE
Item of enumerated type not found (SynCommons from mORMot)

### ISSUE THREAD

**Issue by jaclas** [rfrezino/RFindUnit#42]
Please, see screen:

![ashampoo_snap_2016 06 27_16h00m31s_005_](https://cloud.githubusercontent.com/assets/17312717/16382788/91b67064-3c82-11e6-9bc1-74c2319f1ef3.png)

**Comment by jaclas** [comment]
Other example:

![ashampoo_snap_2016 07 05_14h41m01s_001_](https://cloud.githubusercontent.com/assets/17312717/16584968/ce17a25c-42be-11e6-8875-1025b56868cc.png)

**Comment by rrezino** [comment]
Yes Jaclas, it do not look for the specific value of the enumerator, it looks for the enumerator name.
In these cases, TInstanceKind and TSynLogInfo... but it's a good idea to get it.

**Comment by rrezino** [comment]
I recommend you to get the new version. I fixed some issues.

**Comment by jaclas** [comment]
This issue (items of enumerated types) is still not implemented?

**Comment by rrezino** [comment]
hahaha no it's not, it's not that easy to implement this. And now, i really don't know how to deal with that, because there are some many values like that that you pollute the result.

**Comment by jaclas** [comment]
This is a good reason to expand the weight calculator :-)
I suggest that the results list should show only those items that exceed a certain weight value (or all if not much).
Let enum has less weight than the normal item. If the enum will be fully compliant then obtain a high weight (eg. when user enter the full name) and will appear in the results list.
This also solve the problem too many items in the results.

**Comment by rrezino** [comment]
I added the enum and set values
